version: "3"

services:
  producer:
    image: sites-availability:latest
    build: .
    volumes:
      - ./producer:/app
      - ./common:/app
    environment:
#      - KAFKA_BROKER "localhost"
#      - KAFKA_PORT = 9092
#      - KAFKA_AUTO_OFFSET_RESET = "latest"
#      - KAFKA_KEY = "python-shell"
#      - KAFKA_MAX_REQUEST_SIZE = 2000000
  consumer:
    image: sites-availability:latest
    build: .
    volumes:
      - ./consumer:/app
      - ./common:/app
    environment:
  #      - KAFKA_BROKER "localhost"
  #      - KAFKA_PORT = 9092
  #      - KAFKA_AUTO_OFFSET_RESET = "latest"
  #      - KAFKA_KEY = "python-shell"
  #      - KAFKA_MAX_REQUEST_SIZE = 2000000
