version: '3'

volumes:
  site_availability_postgres_data:
    driver: local

services:
  postgres:
    image: postgres:12.7
    volumes:
      - site_availability_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sites
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432